name: build

on: 
  workflow_dispatch:

jobs:
  build:
    name: Build CubeSX/WiiSX
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - name: Checkout pcsxgc
      uses: actions/checkout@master
      with:
        path: pcsxgc

    - name: Checkout libogc2
      uses: actions/checkout@main
      with:
        repository: emukidid/libogc
        path: libogc

    - name: add ppc gcc to PATH environment variable
      uses: myci-actions/export-env-var@1
      with:
        name: PATH
        value: $PATH:/opt/devkitpro/devkitPPC/bin

    - name: Export CFLAGS
      uses: myci-actions/export-env-var@1
      with:
        name: CFLAGS
        value: -O3 -fipa-pta -flto -DNDEBUG

    - name: Export CXXFLAGS
      uses: myci-actions/export-env-var@1
      with:
        name: CXXFLAGS
        value: -O3 -fipa-pta -flto -DNDEBUG

    - name: Checkout libfat
      uses: actions/checkout@main
      with:
        repository: extremscorner/libfat
        path: libfat

    - name: Build libogc2
      run: make install
      working-directory: libogc

    - name: Build libfat
      run: make ogc-install
      working-directory: libfat

    - name: Copy release files
      run: |
        cp -r Gamecube/release release
        cp -r Gamecube/release release_gx
        cp -r Gamecube/release release_unai
      working-directory: pcsxgc

    - name: Build WiiSX (peops gfx)
      run: |
        mkdir build_wii
        cmake -B build_wii -DCMAKE_BUILD_TYPE=None -DWIISX_TARGET=NintendoWii -DGPU_PLUGIN=Peops
        cd build_wii
        make -j42069
        mv WiiSX.dol release_wii/apps/wiiSX/boot.dol
      working-directory: pcsxgc

    - name: Build WiiSX (gx gpu)
      run: |
        mkdir build_wii_gx
        cmake -B build_wii_gx -DCMAKE_BUILD_TYPE=None -DWIISX_TARGET=NintendoWii -DGPU_PLUGIN=PeopsGX
        cd build_wii_gx
        make -j42069
        mv WiiSX.dol release_wii_gx/apps/wiiSX/boot.dol
      working-directory: pcsxgc

    - name: Build WiiSX (unai gpu)
      run: |
        mkdir build_wii_unai
        cmake -B build_wii_unai -DCMAKE_BUILD_TYPE=None -DWIISX_TARGET=NintendoWii -DGPU_PLUGIN=Unai
        cd build_wii_unai
        make -j42069
        mv WiiSX.dol release_wii_unai/apps/wiiSX/boot.dol
      working-directory: pcsxgc

    - name: Build CubeSX (soft gfx)
      run: |
        mkdir build_cube
        cmake -B build_cube -DCMAKE_BUILD_TYPE=None -DWIISX_TARGET=NintendoGameCube -DGPU_PLUGIN=Peops
        cd build_cube
        make -j42069
        mv CubeSX.dol release_soft/CubeSX.dol
      working-directory: pcsxgc

    - name: Build CubeSX (gx gpu)
      run: |
        mkdir build_cube_gx
        cmake -B build_cube_gx -DCMAKE_BUILD_TYPE=None -DWIISX_TARGET=NintendoGameCube -DGPU_PLUGIN=PeopsGX
        cd build_cube_gx
        make -j42069
        mv CubeSX.dol release_gx/CubeSX.dol
      working-directory: pcsxgc

    - name: Build CubeSX (unai gpu)
      run: |
        mkdir build_cube_unai
        cmake -B build_cube_unai -DCMAKE_BUILD_TYPE=None -DWIISX_TARGET=NintendoGameCube -DGPU_PLUGIN=Unai
        cd build_cube_unai
        make -j42069
        mv CubeSX.dol release_unai/CubeSX.dol
      working-directory: pcsxgc

    - name: Upload soft (Peops) CubeSX/WiiSX
      uses: actions/upload-artifact@main
      with:
        name: WiiSX
        path: pcsxgc/release

    - name: Upload GX CubeSX/WiiSX
      uses: actions/upload-artifact@main
      with:
        name: WiiSX_GX
        path: pcsxgc/release_gx

    - name: Upload soft (Unai) CubeSX/WiiSX
      uses: actions/upload-artifact@main
      with:
        name: WiiSX_Unai
        path: pcsxgc/release_unai
